#!/bin/bash
. "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/autoexec" || exit 1

EXTENSION=". \"$BC_C9_LIBRARY/autoexec\""

BASHRC_FILEPATH="$HOME/.bashrc"
if grep -r "^$EXTENSION$" "$BASHRC_FILEPATH" > /dev/null; then
    echo "$BC_C9_NAME: install: info: ~/.bashrc extension already installed. skipping."
else
    echo "$EXTENSION" >> "$BASHRC_FILEPATH"
    INSTALLED=1
fi

PROFILE_FILEPATH="$HOME/.profile"
if grep -r "^$EXTENSION$" "$PROFILE_FILEPATH" > /dev/null; then
    echo "$BC_C9_NAME: install: info: ~/.profile extension already installed. skipping."
else
    echo "$EXTENSION" >> "$PROFILE_FILEPATH"
    INSTALLED=1
fi

if diff "$BC_C9_LIBRARY/assets/gitignore" "$HOME/.gitignore" > /dev/null; then
    echo "$BC_C9_NAME: install: info: ~/.gitignore replacement already installed. skipping."
else
    cp "$BC_C9_LIBRARY/assets/gitignore" "$HOME/.gitignore"
    INSTALLED=1
fi

if [ -z "$(git config --global 'url.git@github.com:.insteadOf')" ]; then
    git config --global 'url.git@github.com:.insteadOf' 'https://github.com/'
    INSTALLED=1
else
    echo "$BC_C9_NAME: install: info: ~/.gitconfig github.com extension already installed. skipping."
fi

nvm i 8

if ! [ -z "$INSTALLED" ]; then
    printf "Installation finished.\nRun \"source \"$BC_C9_LIBRARY/autoexec\"\" or start a new terminal.\n"
fi
